AllCops:
  TargetRubyVersion: 3.4.1
  TargetRailsVersion: 8.0.1
  Exclude:
    - "db/migrate/**/*"
    - "db/*schema.rb"
    - "tmp/**/*"
    - "log/**/*"
    - "vendor/**/*"
    - "bin/**/*"
inherit_from:
  - .rubocop_todo.yml
